name: CI - SQLFluff & dbt build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./olist

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install dbt-bigquery==1.12.0 sqlfluff==4.2.2 sqlfluff-templater-dbt==4.2.2

      - name: Authenticate to Google Cloud
        env:
          # Pasamos el secret a una variable de entorno primero (es más seguro para el JSON)
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > $HOME/gcp-sa-key.json

      - name: Setup dbt profile for CI
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          olist:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: data-eng-portfolio-503716
                dataset: dbt_ci_testing
                threads: 4
                keyfile: $HOME/gcp-sa-key.json
                location: US
          EOF

      - name: Install dbt packages
        run: dbt deps

      - name: Run SQLFluff Lint
        run: sqlfluff lint models/

      - name: Run dbt build
        run: dbt build --target ci